version: "2.4"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: "3"
    environment:
      - "MONGO_LOG_DIR=/dev/null"
      - "MONGO_INITDB_ROOT_USERNAME=$MONGO_USER"
      - "MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS"
    command: --auth
    volumes:
      - "./mongodb/:/data/db"

  kalah:
    image: ghcr.io/ivan-fedorov/kalah-game
    container_name: kalah-game
    depends_on:
      - mongodb
    environment:
      - "TELEGRAM_TOKEN=$TELEGRAM_TOKEN"
      - "MONGO_USER=$MONGO_USER"
      - "MONGO_PASS=$MONGO_PASS"