version: "2.4"
services:
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    ports:
      - "27017:27017"
    logging: &default_logging
      driver: json-file
      options:
        max-size: 10M
        max-file: "3"
    environment:
      - "MONGO_LOG_DIR=/dev/null"
      - "MONGO_INITDB_ROOT_USERNAME=$MONGO_USER"
      - "MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS"
    command: --auth
    volumes:
      - "./mongodb/:/data/db"

  kalah:
    image: ghcr.io/ivan-fedorov/kalah-game
    container_name: kalah-game
    depends_on:
      - mongodb
    logging: *default_logging
    environment:
      - "TELEGRAM_TOKEN=$TELEGRAM_TOKEN"
      - "MONGO_USER=$MONGO_USER"
      - "MONGO_PASS=$MONGO_PASS"

  grafana:
    container_name: grafana
    image: grafana/grafana:8.1.1
    logging: *default_logging
#    volumes:
#      - ./grafana/dashboards/:/var/lib/grafana/dashboards
#      - ./grafana/provisioning/:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${MONITORING_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${MONITORING_PASSWORD}

  prometheus:
    image: prom/prometheus:v2.29.1
    container_name: prometheus
    restart: always
    #    ports:
    #     - 9090:9090
    logging: *default_logging
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.retention.size=512MB
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    mem_limit: 200M

